version: "3.9"

services:

  wiki-sinp-nginx:
    image: nginx:1.24.0-bullseye
    # https://hub.docker.com/_/nginx
    container_name: wiki-sinp-nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:50084:80"
    depends_on:
      - wiki-sinp-dokuwiki
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - dokuwiki-storage:/var/www/html
      - data-dokuwiki-storage:/var/www/html/data
      - plugins-dokuwiki-storage:/var/www/html/lib/plugins/
      - conf-dokuwiki-storage:/var/www/html/conf
      - tpl-dokuwiki-storage:/var/www/html/lib/tpl/

  wiki-sinp-dokuwiki:
    build:
      context: ./dokuwiki/build
      dockerfile: Dockerfile
      args:
        # To load backup, uncomment line in dockerfile and set a date instead of "None"
        BACKUP_DATE: "None"
        MSMTP_OVH_PWD: "${MSMTP_OVH_PWD}"
    image: dokuwiki:8.1.19-fpm-bullseye
    # https://hub.docker.com/_/php
    container_name: wiki-sinp-dokuwiki
    env_file: .env
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - dokuwiki-storage:/var/www/html
      - data-dokuwiki-storage:/var/www/html/data
      - plugins-dokuwiki-storage:/var/www/html/lib/plugins/
      - conf-dokuwiki-storage:/var/www/html/conf
      - tpl-dokuwiki-storage:/var/www/html/lib/tpl/

  wiki-sinp-volumerize:
    image: blacklabelops/volumerize:1.7.1
    # https://hub.docker.com/r/blacklabelops/volumerize/tags
    container_name: wiki-sinp-volumerize
    restart: unless-stopped
    environment:
      # Stop containers before backup
      - VOLUMERIZE_CONTAINERS=wiki-sinp-nginx wiki-sinp-dokuwiki
      # Local backup on Host
      - VOLUMERIZE_SOURCE1=/source
      - VOLUMERIZE_TARGET1=file:///backup
      - VOLUMERIZE_CACHE1=/volumerize-cache/local
      # Schedule backup
      - TZ=Europe/Paris
      - VOLUMERIZE_JOBBER_TIME=0 0 3 * * *
      - VOLUMERIZE_FULL_IF_OLDER_THAN=7D
      #- VOLUMERIZE_DUPLICITY_OPTIONS=--dry-run
      # Remove old backups
      - JOB_NAME2=RemoveOldBackups
      - JOB_COMMAND2=/etc/volumerize/remove-older-than 7D --force
      - JOB_TIME2=0 15 0 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup/:/backup
      - local-backup-cache-storage:/volumerize-cache/local
      - data-dokuwiki-storage:/source/wiki-sinp-data:ro
      - plugins-dokuwiki-storage:/source/wiki-sinp-plugins:ro
      - conf-dokuwiki-storage:/source/wiki-sinp-conf:ro
      - tpl-dokuwiki-storage:/source/wiki-sinp-tpl:ro

volumes:
  dokuwiki-storage:
  data-dokuwiki-storage:
  plugins-dokuwiki-storage:
  conf-dokuwiki-storage:
  tpl-dokuwiki-storage:
  local-backup-cache-storage:
  dropbox-backup-cache-storage:

networks:
  default:
    name: nginx-proxy
    external: true
