#!/bin/bash
# Weekly report
# Parameter : date (format: '%Y-%m-%d) for the report (default : yesterday)
# Run with cron.d (at 04:00 each monday) with : 0 4 * * 1 admin /otp/goaccess-reports/weekly-report
DATE="today"
if [ -n "$1" ]; then # If first parameter passed
    DATE="$1"
fi

YEAR=`date -d "$DATE -1 day" '+%Y'`
MONTH=`date -d "$DATE -1 day" '+%m'`
WEEK=`date -d "$DATE -1 day" '+%V'`
DATE1=`date -d "$DATE -1 day" '+%Y-%m-%d'`
DATE2=`date -d "$DATE -2 days" '+%Y-%m-%d'`
DATE7=`date -d "$DATE -7 days" '+%Y-%m-%d'`

# Create directories structure
docker exec web-log-analyser-goaccess mkdir -p /goaccess/reports/${YEAR}/weeks/${WEEK}/

# Test yesterday gzip file or not
isGz="false"
yesterdayFile="/goaccess/logs/access.log.${DATE1}"
result=`docker exec web-log-analyser-goaccess sh -c \
	"test -f '${yesterdayFile}.gz' && echo 'pass' || echo 'fail'"`
if [ "${result//[$'\r\n']}" = 'pass' ]; then
    yesterdayFile="${yesterdayFile}.gz"
	isGz="true"
fi

# Get last week gzip files
gzFiles=`docker exec web-log-analyser-goaccess sh -c \
	"find /goaccess/logs/access.log.*.gz \
		-newer /goaccess/logs/access.log.${DATE7}.gz \
		-not -newer /goaccess/logs/access.log.${DATE2}.gz"`
#echo "${gzFiles//[$'\t\r\n']/ }"

# Print URL 
echo "See report: https://web-log-analyser.silene.eu/${YEAR}/weeks/${WEEK}/index.html"

# Generate report
echo "Log parsing:"
if [ "$isGz" = 'true' ]; then
	docker exec web-log-analyser-goaccess sh -c "zcat ${yesterdayFile} ${gzFiles//[$'\t\r\n']/ } | \
		goaccess --config-file=/goaccess/goaccess.cli.conf \
			--output=/goaccess/reports/${YEAR}/weeks/${WEEK}/index.html -"
else
	docker exec web-log-analyser-goaccess sh -c "zcat ${gzFiles//[$'\t\r\n']/ } | \
		goaccess --config-file=/goaccess/goaccess.cli.conf \
			--log-file=${yesterdayFile} \
			--output=/goaccess/reports/${YEAR}/weeks/${WEEK}/index.html -"
fi
