#!/bin/bash
# Weekly report
# Parameter : date (format: '%Y-%m-%d) for the report (default : yesterday)
# Run with cron.d (at 04:00 each monday) with : 0 4 * * 1 admin /otp/goaccess-reports/weekly-report
DATE="today"
if [ -n "$1" ]; then # If first parameter passed
    DATE="$1"
fi

YEAR=`date -d "$DATE -1 day" '+%Y'`
MONTH=`date -d "$DATE -1 day" '+%m'`
WEEK=`date -d "$DATE -1 day" '+%V'`
DATE1=`date -d "$DATE -1 day" '+%Y-%m-%d'`
DATE2=`date -d "$DATE -2 days" '+%Y-%m-%d'`
DATE7=`date -d "$DATE -7 days" '+%Y-%m-%d'`

# Create directories structure
docker exec -it web-log-analyser-goaccess mkdir -p /goaccess/reports/${YEAR}/weeks/${WEEK}/

# Generate report
#docker exec -it web-log-analyser-goaccess sh -c "zcat -f `find /goaccess/logs/ -name "access.log.*.gz" -mtime -7` | goaccess --log-file=/goaccess/logs/access.log.${YEAR}-${MONTH}-${D1} --config-file=/goaccess/goaccess.cli.conf --output=/goaccess/reports/${YEAR}/weeks/${WEEK}/index.html -"

# Test yesterday gzip file or not
yesterdayFile="/goaccess/logs/access.log.${DATE1}"
result=`docker exec -it web-log-analyser-goaccess sh -c "test -f '${yesterdayFile}.gz' && echo 'pass' || echo 'fail'"`
if [ "${result//[$'\r\n']}" = 'pass' ]; then
    yesterdayFile="${yesterdayFile}.gz"
fi

# Get last week gzip files
gzFiles=`docker exec -it web-log-analyser-goaccess sh -c "find /goaccess/logs/access.log.*.gz -newer /goaccess/logs/access.log.${DATE7}.gz -not -newer /goaccess/logs/access.log.${DATE2}.gz"`
#echo "${gzFiles//[$'\t\r\n']/ }"

# Generate report
docker exec -it web-log-analyser-goaccess sh -c "zcat -f ${yesterdayFile} ${gzFiles//[$'\t\r\n']/ } | goaccess --config-file=/goaccess/goaccess.cli.conf --output=/goaccess/reports/${YEAR}/weeks/${WEEK}/index.html -"
