version: "3.9"

services:
  sftp:
    image: atmoz/sftp:debian
    container_name: sftp
    ports:
      - "${HOST_SSH_PORT}:22"
    restart: unless-stopped
    volumes:
      - ./ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./users.conf:/etc/sftp/users.conf:ro
      - /data/sftp-data:/home/data
      - /data/sftp-data:/home/data-reader

networks:
  default:
    name: nginx-proxy
    external: true

