version: "3.7"

services:
  monitor-influxdb:
    image: influxdb:1.7.9
    # https://hub.docker.com/_/influxdb
    container_name: monitor-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
      - "8089:8089/udp"
    hostname: ${HOSTNAME_INFLUXDB:-influxdb-paca-sinp}
    env_file:
      - ./influxdb/.env.influxdb
    networks:
      - nginx-proxy
    volumes:
      - influxdb-storage:/var/lib/influxdb/data

  monitor-telegraf:
    image: telegraf:1.13.2
    # https://hub.docker.com/_/telegraf
    container_name: monitor-telegraf
    restart: unless-stopped
    depends_on:
      - monitor-influxdb
    ports:
      - "127.0.0.1:8125:8125/udp"
    hostname: ${HOSTNAME:-web-paca-sinp}
    environment:
      HOST_ETC: /host/etc
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_VAR: /host/var
      HOST_RUN: /host/run
      HOST_MOUNT_PREFIX: /host
    networks:
        - nginx-proxy
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /:/host:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/srvstatus/status.json:/opt/srvstatus/status.json

  monitor-grafana:
    image: grafana/grafana:6.6.1
    # https://hub.docker.com/r/grafana/grafana
    container_name: monitor-grafana
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ./grafana/.env.grafana
    depends_on:
      - monitor-influxdb
    networks:
      - nginx-proxy
    volumes:
        - grafana-storage:/var/lib/grafana

  monitor-grafana-backup:
    image: ysde/docker-grafana-backup-tool:latest
    # https://hub.docker.com/r/ysde/docker-grafana-backup-tool
    container_name: monitor-grafana-backup
    restart: "no"
    depends_on:
      - monitor-grafana
    networks:
      - nginx-proxy
    environment:
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
      - GRAFANA_URL=http://monitor-grafana:3000
    volumes:
       - ./grafana/backup:/opt/grafana-backup-tool/_OUTPUT_

volumes:
  grafana-storage:
  influxdb-storage:

networks:
  nginx-proxy:
    external: true

