version: "3.9"

services:
  analytics-nginx:
    image: nginx:1.26.0-bookworm
    # https://hub.docker.com/_/nginx
    container_name: analytics-nginx
    restart: unless-stopped
    expose:
      - 80
    depends_on:
      - analytics-matomo
    environment:
      VIRTUAL_HOST: analytics.silene.eu
      LETSENCRYPT_HOST: analytics.silene.eu
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 3s
      timeout: 2s
      retries: 3
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - matomo-storage:/var/www/html

  analytics-matomo:
    build:
      context: ./matomo/build
      dockerfile: Dockerfile
    image: cbna/matomo:5.0.3-fpm
    # https://hub.docker.com/_/matomo
    container_name: analytics-matomo
    restart: unless-stopped
    depends_on:
      - analytics-mariadb
    expose:
      - 9000
    env_file: .env
    environment:
      - MATOMO_DATABASE_HOST=analytics-mariadb
      - MATOMO_DATABASE_ADAPTER=${MATOMO_DATABASE_ADAPTER}
      - MATOMO_DATABASE_TABLES_PREFIX=${MATOMO_DATABASE_TABLES_PREFIX}
      - MATOMO_DATABASE_USERNAME=${MYSQL_USER}
      - MATOMO_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - MATOMO_DATABASE_DBNAME=${MYSQL_DATABASE}
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 5s
      timeout: 1s
      retries: 3
    volumes:
      # - ./logs:/var/www/html/logs
      #- ./matomo/config/config.ini.php:/var/www/html/config/config.ini.php:rw
      - matomo-storage:/var/www/html

  analytics-mariadb:
    image: mariadb:11.3.2-jammy
    # https://hub.docker.com/_/mariadb
    container_name: analytics-mariadb
    restart: unless-stopped
    expose:
      - 3306
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # See : https://github.com/docker-library/mariadb/issues/160
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -P 3306 -p${MYSQL_ROOT_PASSWORD} | grep 'mysqld is alive' || exit 1"]
      interval: 2s
      retries: 5
    volumes:
      - ./mariadb/my.override.cnf:/etc/mysql/conf.d/matomo.cnf
      - db-storage:/var/lib/mysql
      #- ./mariadb/initdb.d/:/docker-entrypoint-initdb.d/

volumes:
  db-storage:
  matomo-storage:

networks:
  default:
    name: nginx-proxy
    external: true
