version: "3.9"

# To restore :
#   1. Stop container : docker compose stop cms-volumerize
#   2. Verify diff : docker compose -f docker-compose.restore.yml run cms-volumerize-restore-from-local verify
#   3. To restore execute : docker-compose -f docker-compose.restore.yml run cms-volumerize-restore restore
#   4. Only if necessary, restart containers : docker-compose restart cms-nginx cms-wordpress cms-mariadb cms-adminer cms-volumerize
#   5. Check restoration

services:
  cms-volumerize-restore-from-local:
    image: blacklabelops/volumerize:1.7.1
    # https://hub.docker.com/r/blacklabelops/volumerize/tags
    container_name: cms-volumerize-restore-from-local
    restart: "no"
    environment:
      # Stop containers before backup
      - VOLUMERIZE_CONTAINERS=cms-nginx cms-wordpress cms-mariadb cms-adminer cms-volumerize
      # Local backup on Host
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=file:///backup
      - VOLUMERIZE_CACHE=/volumerize-cache/local
      #- VOLUMERIZE_DUPLICITY_OPTIONS=--dry-run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup/:/backup:ro
      - local-backup-cache-storage:/volumerize-cache/local
      - wordpress-storage:/source/cms-wordpress
      - db-storage:/source/cms-mariadb
    command: verify

volumes:
  local-backup-cache-storage:
  dropbox-backup-cache-storage:
  db-storage:
  wordpress-storage:

networks:
  default:
    name: nginx-proxy
    external: true
