version: "3.7"

# To restore : 
#   1. Stop container : docker-compose stop cms-volumerize
#   2. Verify diff : docker-compose -f docker-compose.restore.yml run cms-volumerize-restore-from-<local-or-dropbox> verify
#   3. To restore execute : docker-compose -f docker-compose.restore.yml run cms-volumerize-restore restore
#   4. Only if necessary, restart containers : docker-compose restart cms-nginx cms-wordpress cms-mariadb cms-adminer cms-volumerize
#   5. Check restoration
services:
  cms-volumerize-restore-from-local:
    image: blacklabelops/volumerize:1.5.1
    # https://hub.docker.com/r/blacklabelops/volumerize/tags
    container_name: cms-volumerize-restore-from-local
    restart: "no"
    environment:
      # Stop containers before backup
      - VOLUMERIZE_CONTAINERS=cms-nginx cms-wordpress cms-mariadb cms-adminer cms-volumerize
      # Local backup on Host
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=file:///backup
      - VOLUMERIZE_CACHE=/volumerize-cache
      #- VOLUMERIZE_DUPLICITY_OPTIONS=--dry-run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup/:/backup:ro
      - backup-cache-storage:/volumerize-cache
      - wordpress-storage:/source/cms-wordpress
      - db-storage:/source/cms-mariadb
    command: verify

  cms-volumerize-restore-from-dropbox:
    image: blacklabelops/volumerize:1.5.1
    # https://hub.docker.com/r/blacklabelops/volumerize/tags
    container_name: cms-volumerize-restore-from-dropbox
    restart: "no"
    environment:
      # Stop containers before backup
      - VOLUMERIZE_CONTAINERS=cms-nginx cms-wordpress cms-mariadb cms-adminer cms-volumerize
      # Remote backup on Dropbox
      - DPBX_ACCESS_TOKEN=${DPBX_ACCESS_TOKEN}
      - VOLUMERIZE_SOURCE=/source
      - VOLUMERIZE_TARGET=dpbx:///cms-silene-eu
      - VOLUMERIZE_CACHE=/volumerize-cache
      #- VOLUMERIZE_DUPLICITY_OPTIONS=--dry-run
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backup-cache-storage:/volumerize-cache
      - wordpress-storage:/source/cms-wordpress
      - db-storage:/source/cms-mariadb
    command: verify

volumes:
  backup-cache-storage:
  db-storage:
  wordpress-storage:

networks:
  default:
    external:
      name: nginx-proxy
