version: "3.7"

services:
    telegraf:
        image: telegraf:1.17.3:x
        container_name: telegraf
        restart: unless-stopped
        hostname: ${HOSTNAME:-sinp-paca-db}
        environment:
            HOST_ETC: /host/etc
            HOST_PROC: /host/proc
            HOST_SYS: /host/sys
            HOST_VAR: /host/var
            HOST_RUN: /host/run
            HOST_MOUNT_PREFIX: /host
        networks:
            - nginx-proxy
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /:/host:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /opt/srvstatus/status.json:/opt/srvstatus/status.json

networks:
    nginx-proxy:
        external: true
