version: "3.9"

services:
  nginx-proxy:
    image: nginx:1.24.0-bullseye
    # https://hub.docker.com/_/nginx/
    container_name: nginx-proxy
    hostname: "${HOSTNAME}_nginx-proxy"
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs-storage:/etc/nginx/certs
      - conf-storage:/etc/nginx/conf.d
      - vhost-storage:/etc/nginx/vhost.d
      - html-storage:/usr/share/nginx/html
      - ./docker-gen/vhost.d/location/:/etc/nginx/vhost.d/location/
      - ./docker-gen/vhost.d/server/:/etc/nginx/vhost.d/server/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: 10

  docker-gen:
    image: nginxproxy/docker-gen:0.10.4-debian
    # https://hub.docker.com/r/nginxproxy/docker-gen
    container_name: nginx-proxy-gen
    hostname: "${HOSTNAME}_nginx-proxy-gen"
    depends_on:
      - nginx-proxy
    restart: unless-stopped
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen: "true"
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - certs-storage:/etc/nginx/certs
      - conf-storage:/etc/nginx/conf.d
      - html-storage:/usr/share/nginx/html
      - vhost-storage:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - ./docker-gen/vhost.d/location/:/etc/nginx/vhost.d/location/
      - ./docker-gen/vhost.d/server/:/etc/nginx/vhost.d/server/
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: 10

  nginx-proxy-letsencrypt:
    image: nginxproxy/acme-companion:2.2.8
    container_name: nginx-proxy-letsencrypt
    hostname: "${HOSTNAME}_nginx-proxy-letsencrypt"
    depends_on:
      - docker-gen
    restart: unless-stopped
    environment:
      DEFAULT_EMAIL: adminsys@silene.eu
      NGINX_DOCKER_GEN_CONTAINER: nginx-proxy-gen
      NGINX_PROXY_CONTAINER: nginx-proxy-gen
      # For debug uncomment and set DEBUG value to 1
      #DEBUG: 1
    volumes:
      - certs-storage:/etc/nginx/certs
      - conf-storage:/etc/nginx/conf.d
      - html-storage:/usr/share/nginx/html
      - vhost-storage:/etc/nginx/vhost.d
      - acme-storage:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: json-file
      options:
        max-size: 4m
        max-file: 10

volumes:
  acme-storage:
  certs-storage:
  conf-storage:
  html-storage:
  vhost-storage:

networks:
  default:
    name: nginx-proxy
    external: true
