version: "3.7"

services:
  manager-portainer:
    image: portainer/portainer-ce:2.1.1
    container_name: "manager-portainer"
    restart: unless-stopped
    expose:
      - 8000
    ports:
      - "127.0.0.1:9000:9000"
    hostname: ${HOSTNAME:-sinp-paca-web}
    command: --admin-password ${ENCRYPTED_PASSWORD}
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-storage:/data

volumes:
  portainer-storage:

networks:
  default:
    external:
      name: ${NETWORK:-nginx-proxy}
