version: "3.7"

services:

  wiki-sinp-nginx:
    image: nginx:1.16.1
    # https://hub.docker.com/_/nginx
    container_name: wiki-sinp-nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:50084:80"
    depends_on:
      - wiki-sinp-dokuwiki
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - dokuwiki-storage:/var/www/html
      - data-dokuwiki-storage:/var/www/html/data
      - plugins-dokuwiki-storage:/var/www/html/lib/plugins/
      - conf-dokuwiki-storage:/var/www/html/conf
      - tpl-dokuwiki-storage:/var/www/html/lib/tpl/

  wiki-sinp-dokuwiki:
    build:
      context: ./dokuwiki/build
      dockerfile: Dockerfile
      args:
        BACKUP_DATE: "2020-02-12"
    image: dokuwiki:2018-04-22b-php7.3.14-fpm
    # https://hub.docker.com/_/php
    container_name: wiki-sinp-dokuwiki
    restart: unless-stopped
    expose:
      - 9000
    volumes:
      - dokuwiki-storage:/var/www/html
      - data-dokuwiki-storage:/var/www/html/data
      - plugins-dokuwiki-storage:/var/www/html/lib/plugins/
      - conf-dokuwiki-storage:/var/www/html/conf
      - tpl-dokuwiki-storage:/var/www/html/lib/tpl/

  wiki-sinp-volumerize:
    image: blacklabelops/volumerize:1.5.1
    # https://hub.docker.com/r/blacklabelops/volumerize/tags
    container_name: wiki-sinp-volumerize
    restart: unless-stopped
    environment:
      # Stop containers before backup
      - VOLUMERIZE_CONTAINERS=wiki-sinp-nginx wiki-sinp-dokuwiki
      # Local backup on Host
      - VOLUMERIZE_SOURCE1=/source
      - VOLUMERIZE_TARGET1=file:///backup
      - VOLUMERIZE_CACHE1=/volumerize-cache/local
      # Remote backup on Dropbox
      - DPBX_ACCESS_TOKEN=${DPBX_ACCESS_TOKEN}
      - VOLUMERIZE_SOURCE2=/source
      - VOLUMERIZE_TARGET2=dpbx:///wiki-sinp
      - VOLUMERIZE_CACHE2=/volumerize-cache/dropbox
      # Schedule backup
      - TZ=Europe/Paris
      - VOLUMERIZE_JOBBER_TIME=0 0 3 * * *
      - VOLUMERIZE_FULL_IF_OLDER_THAN=7D
      #- VOLUMERIZE_DUPLICITY_OPTIONS=--dry-run
      # Remove old backups
      - JOB_NAME2=RemoveOldBackups
      - JOB_COMMAND2=/etc/volumerize/remove-older-than 7D --force
      - JOB_TIME2=0 15 0 * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backup/:/backup
      - ./volumerize/docker-entrypoint.sh:/opt/volumerize/docker-entrypoint.sh
      - local-backup-cache-storage:/volumerize-cache/local
      - dropbox-backup-cache-storage:/volumerize-cache/dropbox
      - data-dokuwiki-storage:/source/wiki-sinp-data:ro
      - plugins-dokuwiki-storage:/source/wiki-sinp-plugins:ro
      - conf-dokuwiki-storage:/source/wiki-sinp-conf:ro
      - tpl-dokuwiki-storage:/source/wiki-sinp-tpl:ro

volumes:
  dokuwiki-storage:
  data-dokuwiki-storage:
  plugins-dokuwiki-storage:
  conf-dokuwiki-storage:
  tpl-dokuwiki-storage:
  local-backup-cache-storage:
  dropbox-backup-cache-storage:

networks:
  default:
    external:
      name: nginx-proxy
