version: "3.7"

services:
  web-log-analyser-nginx:
    image: nginx:1.18.0
    # https://hub.docker.com/_/nginx
    container_name: web-log-analyser-nginx
    restart: unless-stopped
    ports:
      - "127.0.0.1:50082:80"
    depends_on:
      - web-log-analyser-goaccess
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - report-storage:/goaccess/reports:ro

  web-log-analyser-goaccess:
    image: allinurl/goaccess:1.5.5
    # https://hub.docker.com/r/allinurl/goaccess
    container_name: web-log-analyser-goaccess
    restart: unless-stopped
    ports:
      - "127.0.0.1:57890:7890"
    volumes:
      - ./goaccess/goaccess.conf:/goaccess/goaccess.conf
      - ./goaccess/goaccess.cli.conf:/goaccess/goaccess.cli.conf
      - /var/log/nginx:/goaccess/logs:ro
      - report-storage:/goaccess/reports:rw
    environment:
      LANG: fr
      TZ: "Europe/Paris"
    entrypoint: sh -c "zcat -f /goaccess/logs/access.log.* /goaccess/logs/access.log.*.gz | goaccess --config-file=/goaccess/goaccess.conf -"

volumes:
  report-storage:

networks:
  default:
    external:
      name: nginx-proxy
